export const locations = [
    {
        name: "Old Simos Restaurant",
        subname: "Cypriot traditional tavern",
        city: "Ammochostos",
        village: "Sotira",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/ux82MU442YL3eW52A",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Odos Sotiros Tavern",
        subname: "Cypriot traditional tavern",
        city: "Ammochostos",
        village: "Sotira",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/NNJKPerSPfEuNkjS9",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Kyriakos Snacks",
        subname: "Cypriot sandwich",
        city: "Ammochostos",
        village: "Paralimni",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/HEhWd97TFKCwDVwy9",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Up 2 You Snack Bar",
        subname: "Cypriot sandwich",
        city: "Ammochostos",
        village: " Ayia Napa",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/XrHnyrNoqUQKnTtLA",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "The Liquid Cafe N Bar",
        subname: "Something a little more formal",
        city: "Ammochostos",
        village: "Agia Napa",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/qqixCz1fKT34KtEt5",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Spartiatis Restaurant",
        subname: "Fish tavern",
        city: "Ammochostos",
        village: "Cape Greco",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/EpwavFgDH913jrVf7",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Robustos Cava",
        subname: "The best coffee in town",
        city: "Ammochostos",
        village: "Paralimni",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/F4TvK7JLooHg3Wau8",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Cape Greco Peninsula",
        subname: "Hiking area",
        city: "Ammochostos",
        village: "Cape Greco",
        category: "Landmarks",
        maps: {
            google: "https://maps.app.goo.gl/HNg4jTgdJs8BThkb7",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Musan Museum",
        subname: "Underwater museum",
        city: "Ammochostos",
        village: "Agia Napa",
        category: "Landmarks",
        maps: {
            google: "https://maps.app.goo.gl/jWXDZ4PrSCUkK2DV7",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Cape Greco Viewpoint",
        subname: "Hiking area",
        city: "Ammochostos",
        village: "Cape Greco",
        category: "Landmarks",
        maps: {
            google: "https://maps.app.goo.gl/UPLWfqdk48sQyM56A",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Caves and Tunnels",
        subname: "Swimming, but not at the beach",
        city: "Ammochostos",
        village: "Cape Greco",
        category: "Sea",
        maps: {
            google: "https://maps.app.goo.gl/WswaeFGyG5YvK1Rs6",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Makronissos Beach",
        subname: "Beach with golden sand",
        city: "Ammochostos",
        village: "Agia Napa",
        category: "Sea",
        maps: {
            google: "https://maps.app.goo.gl/gEnTto3GVNTrWRBAA",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Konnos Beach",
        subname: "Beach with golden sand",
        city: "Cape Greco",
        village: "Agia Napa",
        category: "Sea",
        maps: {
            google: "https://maps.app.goo.gl/qs9i454VXGftqrsj7",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Landa Beach",
        subname: "Beach with golden sand",
        city: "Ammochostos",
        village: "Agia Napa",
        category: "Sea",
        maps: {
            google: "https://maps.app.goo.gl/CiaZYNDPUEDin49P6",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Blue Lagoon",
        subname: "Swimming, but not at the beach",
        city: "Ammochostos",
        village: "Cape Greco",
        category: "Sea",
        maps: {
            google: "https://maps.app.goo.gl/Rz4LKLQTg45MWcyX6",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Buns and Guns",
        subname: "Hamburger restaurant",
        city: "Larnaca",
        village: "Pyla",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/GpWZTkcSWnPWK1et5",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "The Doctor Of Hunger",
        subname: "Cypriot sandwich",
        city: "Larnaca",
        village: "Dhekelia",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/NKPxqsd8t6uJDiSs8",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "To Kazani",
        subname: "Cypriot traditional tavern",
        city: "Larnaca",
        village: "Aradippou",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/MjdX9ppgW8P1TbXd9",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "The Brewing Hand",
        subname: "Beer House",
        city: "Larnaca",
        village: "Chrysopolitissa",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/QELtK4jHpRqkuoMT8",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
    {
        name: "Melitzia Taverna",
        subname: "Cypriot traditional tavern",
        city: "Paphos",
        village: "Tala",
        category: "Food",
        maps: {
            google: "https://maps.app.goo.gl/SGgooMhA9Vhj9cx26",
            apple: "APPLE_LINK",
            open: "OPENSTREETMAP_LINK",
        },
    },
]